## K-nearest neighbors (KNN)

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,KFold
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,\
recall_score,roc_curve,auc

#import expectation_reflection as ER
#from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from function import split_train_test,make_data_balance

In [2]:
np.random.seed(1)

First of all, the processed data are imported.

In [3]:
#data_list = ['1paradox']
#data_list = np.loadtxt('data_list.txt',dtype='str')
data_list = np.loadtxt('data_list_30sets.txt',dtype='str')
#data_list = ['9coag']

print(data_list)

['1paradox' '2peptide' '3stigma' '4nki' '5mental' '6smoking' '7anemia'
 '8language' '9coag' '10tazamia' '11hepato' '12heat' '13ef' '14cervix'
 '15heart' '16liver' '17nwosu' '18school' '19ibs' '21survival'
 '29parkinson' '30paradox2' '31renal' '33svr' '35pcos' '36probiotic'
 '101kidney' '102breast_cancer' '103diabetes_niddk'
 '104diabetic_retinopathy']


In [4]:
def read_data(data_id):    
    data_name = data_list[data_id]
    print('data_name:',data_name)
    Xy = np.loadtxt('../classification_data/%s/data_processed_median.dat'%data_name) 
    X = Xy[:,:-1]
    y = Xy[:,-1]

    #print(np.unique(y,return_counts=True))
    X,y = make_data_balance(X,y)
    print(np.unique(y,return_counts=True))

    X, y = shuffle(X, y, random_state=1)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.5,random_state = 1)
    
    sc = MinMaxScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    return X_train,X_test,y_train,y_test

In [5]:
def measure_performance(X_train,X_test,y_train,y_test):
    
    model = KNeighborsClassifier(algorithm='auto')

    n_neighbors = [3,5,7,9,11,13,15,17]
    
    if len(y_train) <= 10:
        n_neighbors = [2,3,4,5,6,7]    
    
    weights = ['uniform','distance']

    leaf_size = np.linspace(1,10,num=10)
    
    # Create hyperparameter options
    hyper_parameters = dict(n_neighbors=n_neighbors,
                            weights=weights,
                            leaf_size=leaf_size)
    
    # Create grid search using cross validation
    clf = GridSearchCV(model, hyper_parameters, cv=4, iid='deprecated')
    
    # Fit grid search
    best_model = clf.fit(X_train, y_train)
    
    # View best hyperparameters
    #print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
    #print('Best C:', best_model.best_estimator_.get_params()['C'])
    #print('Best alpha:', best_model.best_estimator_.get_params()['alpha'])
    #print('Best l1_ratio:', best_model.best_estimator_.get_params()['l1_ratio'])
    
    # best hyper parameters
    print('best_hyper_parameters:',best_model.best_params_)

    # performance:
    y_test_pred = best_model.best_estimator_.predict(X_test)
    acc = accuracy_score(y_test,y_test_pred)
    #print('Accuracy:', acc)

    p_test_pred = best_model.best_estimator_.predict_proba(X_test) # prob of [0,1]
    p_test_pred = p_test_pred[:,1] # prob of 1    
    fp,tp,thresholds = roc_curve(y_test, p_test_pred, drop_intermediate=False)
    roc_auc = auc(fp,tp)
    #print('AUC:', roc_auc)

    precision = precision_score(y_test,y_test_pred)
    #print('Precision:',precision)

    recall = recall_score(y_test,y_test_pred)
    #print('Recall:',recall)
    
    f1_score = 2*precision*recall/(precision+recall)

    return acc,roc_auc,precision,recall,f1_score

In [6]:
n_data = len(data_list)
roc_auc = np.zeros(n_data)   ; acc = np.zeros(n_data)
precision = np.zeros(n_data) ; recall = np.zeros(n_data)
f1_score = np.zeros(n_data)

#data_id = 0
for data_id in range(n_data):
    X_train,X_test,y_train,y_test = read_data(data_id)
    acc[data_id],roc_auc[data_id],precision[data_id],recall[data_id],f1_score[data_id] =\
           measure_performance(X_train,X_test,y_train,y_test)
    print(data_id,acc[data_id],roc_auc[data_id],precision[data_id],recall[data_id],f1_score[data_id])    
    

data_name: 1paradox
(array([-1.,  1.]), array([60, 60]))
best_hyper_parameters: {'leaf_size': 1.0, 'n_neighbors': 11, 'weights': 'uniform'}
0 0.65 0.7591069330199764 0.5263157894736842 0.8695652173913043 0.6557377049180327
data_name: 2peptide
(array([-1.,  1.]), array([23, 23]))
best_hyper_parameters: {'leaf_size': 1.0, 'n_neighbors': 7, 'weights': 'uniform'}
1 0.8695652173913043 0.9769230769230769 1.0 0.7 0.8235294117647058
data_name: 3stigma
(array([-1.,  1.]), array([2725, 2725]))
best_hyper_parameters: {'leaf_size': 4.0, 'n_neighbors': 5, 'weights': 'distance'}
2 0.9023853211009174 0.9704250276079404 0.9981949458483754 0.8072992700729927 0.8926553672316384
data_name: 4nki
(array([-1.,  1.]), array([77, 77]))
best_hyper_parameters: {'leaf_size': 1.0, 'n_neighbors': 13, 'weights': 'uniform'}
3 0.6103896103896104 0.7913223140495868 0.7916666666666666 0.4318181818181818 0.5588235294117647
data_name: 5mental
(array([-1.,  1.]), array([147, 147]))
best_hyper_parameters: {'leaf_size': 1.0

In [7]:
print('acc_mean:',acc.mean())
print('roc_mean:',roc_auc.mean())
print('precision:',precision.mean())
print('recall:',recall.mean())
print('f1_score:',f1_score.mean())

acc_mean: 0.7504541861388259
roc_mean: 0.8236284715120689
precision: 0.8011621413047787
recall: 0.7011457783960897
f1_score: 0.7285492588521578


In [8]:
np.savetxt('result_KNN_median.dat',(roc_auc,acc,precision,recall,f1_score),fmt='%f')