In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# features
x = np.array([[8,5,2],[13,3,10],[15,4,6],[18,3,15],[20,5,4]])
print(x)

# target
y = np.array([40,60,80,52,78])
print(y)

[[ 8  5  2]
 [13  3 10]
 [15  4  6]
 [18  3 15]
 [20  5  4]]
[40 60 80 52 78]


In [3]:
# Create model
reg = LinearRegression()

In [4]:
# Fit training data
reg = reg.fit(x,y)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)


In [5]:
# coefficient
c = reg.coef_
print(c)

[  4.62160254 -30.09459936  -7.38122132]


In [6]:
# intercept
b = reg.intercept_
print(b)

168.5997176138369


In [7]:
# predict y
ypred = reg.predict(x)
print(ypred)

[40.33709848 64.58453936 73.25803036 50.78644546 81.03388634]


In [8]:
# r2 score
r2 = reg.score(x,y)
print(r2)

0.933850195107563


In [9]:
# actual vs predicted
plt.plot([y.min(),y.max()],[y.min(),y.max()],'r--')
plt.scatter(y,ypred)
plt.xlabel('y')
plt.ylabel('predicted y')