In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
#from matplotlib.colors import ListedColormap
#import matplotlib.pyplot as plt
#from matplotlib import rcParams

In [2]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [3]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [4]:
sc = StandardScaler()

# fit the scaler to the training feature set ONLY
sc.fit(X_train)

# scale (transform) the training and the testing sets
# using the scaler that was fitted to training data
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [5]:
np.unique(y,return_counts= True)

(array([0, 1, 2]), array([50, 50, 50]))

In [6]:
X_train_std.shape

(105, 4)

In [7]:
X_test_std.shape

(45, 4)

In [8]:
# create the perceptron instance
#model = Perceptron(max_iter=40,tol=None,eta0=0.1,random_state=0)
model = MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(5,2),random_state=0)

# fit
model.fit(X_train_std,y_train)

# make predictions
y_pred = model.predict(X_test_std)

acc = accuracy_score(y_test,y_pred)
print(acc)

0.9777777777777777


In [9]:
model.coefs_

[array([[ 1.6101828 , -2.69889761, -2.55158074, -0.15416411, -0.17205947],
        [-0.15206368,  4.64741542,  0.70471316, -2.05535262, -0.2381651 ],
        [-7.28992093, -4.6688559 , -2.68161969,  3.1580225 , -0.74481428],
        [-3.07441712, -4.89058725, -2.44395298,  1.06213981,  0.56511967]]),
 array([[ 4.03251901, -4.10979071],
        [ 7.00710415, -0.97513581],
        [ 0.28064232,  6.47957304],
        [-0.4911145 ,  8.48928846],
        [ 0.17487506, -0.89093657]]),
 array([[ 4.96520218,  4.72087469, -8.05949549],
        [-2.46380385, -0.7923296 ,  3.24336412]])]

In [10]:
# weights
# from input to hidden layer 1
model.coefs_[0].shape

(4, 5)

In [11]:
# from hidden layer 1 to hidden layer 2
model.coefs_[1].shape

(5, 2)

In [12]:
# from hidden layer 2 to output
model.coefs_[2].shape

(2, 3)